### ISSUE TITLE
Request/Idea

### ISSUE THREAD

**Issue by PATRONIOO** [SnowSnakz/ElementalFoods#3]
Hello developer, I would like to ask you to add the ability to disable a value in the description that shows how much it restores hunger

**Comment by SnowSnakz** [comment]
This is already a feature. Each item has `show-food-value` which can be set to false to disable the display that you mentioned on that item.

**Comment by SnowSnakz** [comment]
I'm going to close this issue because the feature you are requested already exists. 
If my comment above is not what you were looking for, please leave another comment describing the issue in greater detail.
